version: '3.6'

services:
  app:
    image: oskarwestmeijer/weather-api:1.0.0
    container_name: app
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/weather
      - SPRING_DATASOURCE_USERNAME=username1
      - SPRING_DATASOURCE_PASSWORD=password1
networks:
  default:
    name: homepage-proxy
    external: true